import inspect
import os.path
import shutil
import tempfile
import psrchive

registered_manipulators = ["scruncher", "ddfixfreq"]

auto_import_registered = True # If True, automatically import all registered
                              # manipulators when 'manipulators' is
                              # imported.

__all__ = registered_manipulators

plugin_name = NotImplemented

def run_manipulator(manipulator_func, infns, cmdopts, \
                        outname=None, tmpdir=None):
    """Set up a temporary directory to run the manipulator
        method in, load the archives, run the manipulator,
        get the result of the manipulator, break down the
        temporary directory and return the result of the
        manipulation.

        Inputs:
            manipulator_func: The manipulator function to use. 
            infns: Names of the input files to be passed to the
                manipulator
            cmdopts: argparse.Namespace object generated by
                parsing commandline options. The appropriate
                arguments are passed to the manipulator.
            outname: File to unload manipulated archive to.
                (Default: don't unload archive to disk.)
            tmpdir: Location of the temporary directory.
                (Default: let python's 'tempfile' module
                    put the temp dir in a standard location.)

        Outputs:
            manipulated: A psrchive.Archive object that is
                the manipulated archive. This archive should
                be written out to disk my the user.
    """
    workdir = tempfile.mkdtemp(dir=tmpdir, suffix='epta_toa_db')
    archives = []
    for fn in infns:
        newfn = os.path.join(workdir, os.path.split(fn)[-1])
        shutil.copy(fn, newfn)
        archives.append(psrchive.Archive_load(newfn))
    try:
        print "Running %s" % cmdopts.manipulator
        print "With %s archives" % len(archives)
        print "And arguments %s" % cmdopts
        args = inspect.getargspec(manipulator_func)[0]
        kwargs = {}
        for arg in args:
            if arg != "archives":
                kwargs[arg] = getattr(cmdopts, arg)
        manipulated = manipulator_func(archives, **kwargs)
    finally:
        shutil.rmtree(workdir)
    if outname is not None:
        manipulated.unload(outname)
    return manipulated


if auto_import_registered:
    for manipulator in registered_manipulators:
        __import__(manipulator, globals())
