create table if not exists rawfiles (
	rawfile_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	filename varchar(512) not null,
	filepath varchar(512) not null,	
	md5sum varchar(64) not null,
	add_time DATETIME not null,
	user_id bigint not null,
	comments text,
	pulsar_id bigint not null,	
	obssystem_id bigint not null,
	nbin mediumint unsigned,
	nchan mediumint unsigned,
	npol tinyint unsigned,
	nsubint tinyint unsigned,
	type varchar(32),
	site varchar(8),
	name varchar(16),
	datatype varchar(32),
	coord char(32),
	freq float,
	bw float,
	dm float,
	rm float,
	dmc float,
	rmc float,
	polc float,
	scale varchar(16),
	state varchar(16),
	length float,
	int_nchan mediumint unsigned,
	int_npol tinyint unsigned,
	int_nbin mediumint unsigned,
	int_imjd smallint unsigned,
	int_fmjd double,
	int_duration float,
	int_period double,
	int_freq float,
	int_wt float,
	int_point_lst bigint unsigned,
	int_point_gb double,
	int_point_gl double,
	int_point_fa float,
	int_point_pa float,
	int_point_va float,
	int_point_az float,
	int_point_zen float,
	band_nchan mediumint unsigned,
	band_npol tinyint unsigned,
	dspsr_soft varchar(16),
	dspsr_ntot tinyint unsigned,
	dspsr_nblock tinyint unsigned,
	dspsr_nover tinyint unsigned,
	dspsr_state varchar(16),
	dspsr_nfft smallint unsigned,
	dspsr_npos smallint unsigned,
	dspsr_nneg smallint unsigned,
	dspsr_nchan smallint unsigned,
	dspsr_fres tinyint unsigned,
	dspsr_tres tinyint unsigned,
	dspsr_tint tinyint unsigned,
	dspsr_scale mediumint unsigned,
	rcvr_name varchar(16),
	rcvr_basis varchar(16),
	rcvr_hand varchar(4),
	rcvr_sa varchar(8),
	rcvr_rph varchar(8),
	rcvr_fdc varchar(8),
	rcvr_prc varchar(8),
	rcvr_ta float,
	ext_obs_mode varchar(8),
	ext_obsfreq float,
	ext_hdrver varchar(8),
	ext_date varchar(32),
	ext_coord_md varchar(8),
	ext_equinox float,
	ext_trk_mode varchar(8),
	ext_bpa double,
	ext_bmaj double,
	ext_bmin double,
	ext_stt_date varchar(16),
	ext_stt_time varchar(16),
	ext_stt_imjd smallint unsigned,
	ext_stt_smjd mediumint unsigned,
	ext_stt_offs double,
	ext_stt_lst double,
	ext_stt_crd1 varchar(16),
	ext_stt_crd2 varchar(16),
	ext_stp_crd1 varchar(16),
	ext_stp_crd2 varchar(16),
	ext_ra varchar(16),
	ext_dec varchar(16),
	obs_observer varchar(32),
	obs_projid varchar(32),
	itrf_ant_x double,
	itrf_ant_y double,
	itrf_ant_z double,
	be_name varchar(16),
	be_phase tinyint,
	be_dcc tinyint unsigned,
	be_phc tinyint unsigned,
	be_config varchar(128),
	be_nrcvr tinyint unsigned,
	be_tcycle mediumint,
	hist_nrow mediumint unsigned,
	hist_nbin_prd mediumint,
	hist_tbin double,
	hist_chan_bw float,
	dig_ndigr tinyint unsigned,
	dig_npar mediumint unsigned,
	dig_ncycsub smallint unsigned,
	dig_diglev varchar(8),
	DigitiserCounts_dig_mode varchar(8),
	DigitiserCounts_nlev mediumint unsigned,
	DigitiserCounts_npthist mediumint unsigned,
	DigitiserCounts_diglev varchar(8),
	sub_int_type varchar(16),
	sub_int_unit varchar(8),
	sub_tsamp double,
	sub_nbits varchar(8),
	sub_nch_strt mediumint,
	sub_nsblk mediumint,
	sub_nrows mediumint
);
