create table if not exists rawfiles (
	rawfile_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	filename varchar(512) not null,
	filepath varchar(512) not null,	
	md5sum varchar(64) not null,
	add_time DATETIME not null,
	user_id bigint not null,
	comments text,
	pulsar_id bigint not null,	
	obssystem_id bigint not null,
	nbin mediumint unsigned,
	nchan mediumint unsigned,
	npol tinyint unsigned,
	nsub tinyint unsigned,
	type varchar(32),
	site varchar(16),
	name varchar(16),
	datatype varchar(32),
	coord char(32),
	freq float,
	bw float,
	dm float,
	rm float,
	dmc float,
	rmc float,
	polc float,
	scale varchar(16),
	state varchar(16),
	length float,
	rcvr_name varchar(16),
	rcvr_basis varchar(16),
	be_name varchar(16)
);
